### ISSUE TITLE
COMM 130 - Naming Conventions applied to Instructor Resources

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-module-items#16]
Instructor Resources should not be affected by naming conventions (and usually isn't). In this course, it was:

https://byui.instructure.com/courses/11768/modules

**Comment by sethchilders92** [comment]
Ready for review. 

Where it broke in Canvas: https://byui.instructure.com/courses/11768/modules

Applied it to:
Brightspace: https://byui.brightspace.com/d2l/home/225324
Canvas: https://byui.instructure.com/courses/11920/modules
