### ISSUE TITLE
HS 345 - One item was hit with naming conventions twice

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-module-items#17]
Here's the module item:

https://byui.instructure.com/courses/11862/pages/w01-activitytype-w-activitytype-lesson-information?module_item_id=726289

**Comment by sethchilders92** [comment]
The course no longer exists. Do you have the Brightspace OU? @zlw11063

**Comment by sethchilders92** [comment]
Ready for review @zlw11063
