### ISSUE TITLE
Rename "action()"

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-module-items#2]
https://github.com/byuitechops/action-series-module-items/blob/4a69de43c99766e682267e3d049b5e8406822170/actions/module-items-naming-conventions.js#L70-L89

Go ahead and rename this function to make more sense. "Action" is general, which is fine for the grand children that do one thing, but since this one has some complexity to it, lets rename it to something that makes more sense.

**Comment by sethchilders92** [comment]
Changed action( ) to be named modifyModuleItemTitle( )
